name: pubspec_version_cli
description: A Command-Line Interface to replace the version in pubspec.yaml
version: 0.1.0
homepage: https://github.com/lsaudon/pubspec_version_cli
repository: https://github.com/lsaudon/pubspec_version_cli
issue_tracker: https://github.com/lsaudon/pubspec_version_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  file: ^6.1.4 # pub_updater use 6.1.4
  mason_logger: ^0.2.6
  path: ^1.8.3
  pub_updater: ^0.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.3

executables:
  pubspec_version:
