name: pubspec_version_cli
description: A Command-Line Interface to replace the version in pubspec.yaml
version: 0.1.0
homepage: https://github.com/lsaudon/pubspec_version_cli
repository: https://github.com/lsaudon/pubspec_version_cli
issue_tracker: https://github.com/lsaudon/pubspec_version_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: 2.6.0
  cli_completion: 0.5.1
  file: 7.0.1
  mason_logger: 0.3.3
  path: 1.9.1
  pub_updater: 0.5.0
  yaml: 3.1.2

dev_dependencies:
  build_runner: 2.4.15
  build_verify: 3.1.0
  build_version: 2.1.1
  mocktail: 1.0.4
  test: 1.26.0

executables:
  pubspec_version:
