name: pubspec_version_cli
description: Command-Line Interface to change the version in pubspec
version: 0.0.2
homepage: https://github.com/lsaudon/pubspec_version_cli
repository: https://github.com/lsaudon/pubspec_version_cli
issue_tracker: https://github.com/lsaudon/pubspec_version_cli/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  args: ^2.4.0
  cli_completion: ^0.3.0
  file: ^6.1.4
  mason_logger: ^0.2.5
  path: ^1.8.3
  pub_updater: ^0.3.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3 # 2.4.0 need dart sdk > 3.0.0
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.1

executables:
  pubspec_version:
